[mypy]
python_version = 3.9
warn_return_any = False
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = False
warn_no_return = True
strict_equality = True
ignore_missing_imports = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-torch.utils.*]
ignore_missing_imports = True

[mypy-torch.cuda.*]
ignore_missing_imports = True

[mypy-monai.*]
ignore_missing_imports = True

[mypy-torchio.*]
ignore_missing_imports = True

[mypy-deepinv.*]
ignore_missing_imports = True

[mypy-pydicom.*]
ignore_missing_imports = True

[mypy-piq.*]
ignore_missing_imports = True

[mypy-nibabel.*]
ignore_missing_imports = True

[mypy-cv2.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-tensorboard.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-torchvision.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-einops.*]
ignore_missing_imports = True

[mypy-timm.*]
ignore_missing_imports = True
