models:
  bm3d: {}
  common:
    in_channels: 2
    out_channels: 1
  dip: {}
  dncnn:
    pretrained: denoising
  drunet:
    base_channels: 64
  ffdnet:
    nb: 15
    nc: 64
  gsdrunet:
    pretrained: download
  nafnet_large:
    dec_blk_nums:
    - 8
    - 8
    - 8
    - 8
    enc_blk_nums:
    - 8
    - 8
    - 16
    - 32
    middle_blk_num: 48
    width: 64
  nafnet_medium:
    dec_blk_nums:
    - 4
    - 4
    - 4
    - 4
    enc_blk_nums:
    - 4
    - 4
    - 8
    - 16
    middle_blk_num: 24
    width: 64
  nafnet_small:
    dec_blk_nums:
    - 2
    - 2
    - 2
    - 2
    enc_blk_nums:
    - 2
    - 2
    - 4
    - 8
    middle_blk_num: 12
    width: 64
  nafnet_xs:
    dec_blk_nums:
    - 1
    - 1
    - 1
    - 1
    enc_blk_nums:
    - 1
    - 1
    - 1
    - 14
    middle_blk_num: 1
    width: 64
  restormer:
    pretrained: denoising
  scunet:
    config: A
  swinir:
    window_size: 8
  unet:
    bilinear: false
    features:
    - 64
    - 128
    - 256
    - 512
  se_scunet_mini:
    config: [1,1,1,1,1,1,1]
    dim: 64
