common:
  in_channels: 2
  out_channels: 1

models:
  3d-parallel-ricianet:
    base_filters: 16

data:
  is_3d: true
  patch_size: [64, 64, 64]
  augmentation:
    noise_type: "rician"
    sigma_min: 0.05
    sigma_max: 0.25
    noise_grid_size: 1
    noise_multiplier_min: 1.0
    noise_multiplier_max: 1.0
    
training:
  batch_size: 2
  epochs: 200
  gpu_id: 0
  num_workers: 2
