models:
  common:
    in_channels: 2
    out_channels: 1
  unet:
    features:
    - 64
    - 128
    - 256
    - 512
    bilinear: false
  drunet:
    base_channels: 64
  nafnet_xs:
    width: 64
    enc_blk_nums:
    - 1
    - 1
    - 1
    - 14
    middle_blk_num: 1
    dec_blk_nums:
    - 1
    - 1
    - 1
    - 1
  nafnet_small:
    width: 64
    enc_blk_nums:
    - 2
    - 2
    - 4
    - 8
    middle_blk_num: 12
    dec_blk_nums:
    - 2
    - 2
    - 2
    - 2
  nafnet_medium:
    width: 64
    enc_blk_nums:
    - 4
    - 4
    - 8
    - 16
    middle_blk_num: 24
    dec_blk_nums:
    - 4
    - 4
    - 4
    - 4
  nafnet_large:
    width: 64
    enc_blk_nums:
    - 8
    - 8
    - 16
    - 32
    middle_blk_num: 48
    dec_blk_nums:
    - 8
    - 8
    - 8
    - 8
  scunet:
    config: A
  restormer:
    pretrained: denoising
  gsdrunet:
    pretrained: download
  dncnn:
    pretrained: denoising
  swinir:
    window_size: 8
  ffdnet:
    nc: 64
    nb: 15
  bm3d: {}
  dip: {}
